name: english_will_fly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_test:
    sdk: flutter
  get_it: ^8.0.0
  cached_network_image: ^3.4.1
  easy_localization: ^3.0.7
  dio: ^5.7.0
  go_router: ^14.3.0
  shared_preferences: ^2.3.2
  just_audio: ^0.9.42
  flutter_tts: ^4.2.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/
    - assets/image/
    - assets/image/category_icon/
    - assets/image/language/
    - assets/image/level/
    - assets/image/icon/
    - assets/translations/
