name: english_will_fly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  bloc: ^8.1.4
  bloc_test: ^9.1.7
  equatable: ^2.0.5
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  test: ^1.24.9
  get_it: ^7.7.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/
    - assets/image/
