name: english_will_fly
description: "English Short Story Reading App"
publish_to: 'none'
version: 1.0.0+0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  
  # Bloc
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5

  # Firebase
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  firebase_analytics: ^11.4.1
  firebase_crashlytics: ^4.3.1

  # Others
  get_it: ^8.0.0
  cached_network_image: ^3.4.1
  easy_localization: ^3.0.7
  dio: ^5.7.0
  go_router: ^14.3.0
  shared_preferences: ^2.3.2
  just_audio: ^0.9.42
  flutter_tts: ^4.2.0
  translator: ^1.0.3+1
  google_fonts: ^6.2.1
  

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/
    - assets/image/
    - assets/image/category_icon/
    - assets/image/language/
    - assets/image/level/
    - assets/image/icon/
    - assets/image/avatar/
    - assets/translations/
